import "@/app/css/loaders/loader.css";
import "@/app/css/plugins.css";
import "@/app/css/main.css";
import Script from "next/script";
import Header from "@/components/Header";
import Nav from "@/components/Nav";
import GlobalParallax from "@/components/animations/GlobalParallax";
// import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: "Rayo Website",
  description: "Base layout description, gets overridden by pages",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <GlobalParallax />
        <Nav />
        {children}
        {/* <Script src="https://code.jquery.com/jquery-3.7.1.min.js" strategy="beforeInteractive" /> */}
        <Script src="/js/libs.min.js" strategy="afterInteractive" />
        {/* <Script src="/js/app.js" strategy="afterInteractive" /> */}
      </body>
    </html>
  );
}
